alias Wol.{Repo, Organization.Person}

Repo.insert!(%Person{email: "person1@annkissam.com", name: "Person 1"})
Repo.insert!(%Person{email: "person2@annkissam.com", name: "Some other Person 2"})
Repo.insert!(%Person{email: "person3@annkissam.com", name: "Another Person 3"})
Repo.insert!(%Person{email: "person4@annkissam.com", name: "Person 4"})
Repo.insert!(%Person{email: "person5@annkissam.com", name: "Another Person 5"})
Repo.insert!(%Person{email: "person6@annkissam.com", name: "Person 6"})
Repo.insert!(%Person{email: "person7@annkissam.com", name: "Another Person 7"})
Repo.insert!(%Person{email: "person8@annkissam.com", name: "Person 8"})
Repo.insert!(%Person{email: "person9@annkissam.com", name: "Another Person 9"})
Repo.insert!(%Person{email: "person10@annkissam.com", name: "Person 10"})
Repo.insert!(%Person{email: "person11@annkissam.com", name: "Another Person 11"})
Repo.insert!(%Person{email: "person12@annkissam.com", name: "Person 12"})
Repo.insert!(%Person{email: "person13@annkissam.com", name: "Another Person 13"})
Repo.insert!(%Person{email: "person14@annkissam.com", name: "Person 14"})
Repo.insert!(%Person{email: "person15@annkissam.com", name: "Another Person 15"})
Repo.insert!(%Person{email: "person16@annkissam.com", name: "Person 16"})
Repo.insert!(%Person{email: "person17@annkissam.com", name: "Another Person 17"})
Repo.insert!(%Person{email: "person18@annkissam.com", name: "Person 18"})
Repo.insert!(%Person{email: "person19@annkissam.com", name: "Another Person 19"})
Repo.insert!(%Person{email: "person20@annkissam.com", name: "Person 20"})
Repo.insert!(%Person{email: "person21@annkissam.com", name: "Another Person 21"})
Repo.insert!(%Person{email: "person22@annkissam.com", name: "Person 22"})
Repo.insert!(%Person{email: "person23@annkissam.com", name: "Another Person 23"})
Repo.insert!(%Person{email: "person24@annkissam.com", name: "Person 24"})
Repo.insert!(%Person{email: "person25@annkissam.com", name: "Another Person 25"})
Repo.insert!(%Person{email: "person26@annkissam.com", name: "Person 26"})
Repo.insert!(%Person{email: "person27@annkissam.com", name: "Another Person 27"})
Repo.insert!(%Person{email: "person28@annkissam.com", name: "Person 28"})
Repo.insert!(%Person{email: "person29@annkissam.com", name: "Another Person 29"})
Repo.insert!(%Person{email: "person30@annkissam.com", name: "Person 30"})
Repo.insert!(%Person{email: "person31@annkissam.com", name: "Another Person 31"})
Repo.insert!(%Person{email: "person32@annkissam.com", name: "Person 32"})
Repo.insert!(%Person{email: "person33@annkissam.com", name: "Another Person 33"})
Repo.insert!(%Person{email: "person34@annkissam.com", name: "Person 34"})
Repo.insert!(%Person{email: "person35@annkissam.com", name: "Another Person 35"})
Repo.insert!(%Person{email: "person36@annkissam.com", name: "Person 36"})
Repo.insert!(%Person{email: "person37@annkissam.com", name: "Another Person 37"})
Repo.insert!(%Person{email: "person38@annkissam.com", name: "Person 38"})
Repo.insert!(%Person{email: "person39@annkissam.com", name: "Another Person 39"})
Repo.insert!(%Person{email: "person40@annkissam.com", name: "Person 40"})
Repo.insert!(%Person{email: "person41@annkissam.com", name: "Another Person 41"})
Repo.insert!(%Person{email: "person42@annkissam.com", name: "Person 42"})
Repo.insert!(%Person{email: "person43@annkissam.com", name: "Another Person 43"})
Repo.insert!(%Person{email: "person44@annkissam.com", name: "Person 44"})
Repo.insert!(%Person{email: "person45@annkissam.com", name: "Another Person 45"})
Repo.insert!(%Person{email: "person46@annkissam.com", name: "Person 46"})
Repo.insert!(%Person{email: "person47@annkissam.com", name: "Another Person 47"})
Repo.insert!(%Person{email: "person48@annkissam.com", name: "Person 48"})
Repo.insert!(%Person{email: "person49@annkissam.com", name: "Another Person 49"})
Repo.insert!(%Person{email: "person50@annkissam.com", name: "Person 50"})
Repo.insert!(%Person{email: "person51@annkissam.com", name: "Another Person 51"})
Repo.insert!(%Person{email: "person52@annkissam.com", name: "Person 52"})
Repo.insert!(%Person{email: "person53@annkissam.com", name: "Another Person 53"})
Repo.insert!(%Person{email: "person54@annkissam.com", name: "Person 54"})
Repo.insert!(%Person{email: "person55@annkissam.com", name: "Another Person 55"})
Repo.insert!(%Person{email: "person56@annkissam.com", name: "Person 56"})
Repo.insert!(%Person{email: "person57@annkissam.com", name: "Another Person 57"})
Repo.insert!(%Person{email: "person58@annkissam.com", name: "Person 58"})
Repo.insert!(%Person{email: "person59@annkissam.com", name: "Another Person 59"})
Repo.insert!(%Person{email: "person60@annkissam.com", name: "Person 60"})
